# mybox — build the image and drive the quadlet. Everything about how
# the container is composed lives in mybox.container + container/*.conf;
# this file only builds, installs the unit files and gets you a shell.
# The container is disposable (recreated on every restart/boot); state
# persists under /srv/<name>, which mybox.container binds at /.mybox and
# the pre-init turns into an overlay upper for each image-owned tree.

set shell := ["bash", "-euo", "pipefail", "-c"]

mybox_dir := justfile_directory()

# Must match Image= in mybox.container — the published ghcr reference.
# `just build` tags a LOCAL build over it in the ROOTFUL store (the
# system quadlet reads that store; a rootless build is invisible to it).
# Skipping `just build` makes the quadlet pull the published image.
mybox_image := env_var_or_default("MYBOX_IMAGE", "ghcr.io/aboglioli/mybox:latest")

# Unit name: <name>.container → <name>.service, state at /srv/<name>.
mybox_name := env_var_or_default("MYBOX_CONTAINER", "mybox")

# Default user for `enter` / `login` (created at boot by
# mybox-user-setup.service from MYBOX_* env).
mybox_username := env_var_or_default("MYBOX_USERNAME", "user")

# Network: mybox-nat.network (podman bridge + NAT, works anywhere) or
# mybox-lan.network (macvlan — the container is its own host on the LAN).
mybox_netfile := env_var_or_default("MYBOX_NETFILE", "mybox-nat.network")

# Default drop-in set for `just install`. Persistence is NOT here —
# /srv/<name>/{etc,var,home,srv} is part of mybox.container itself and
# cannot be opted out of. 31-nvidia-raw vs 30-nvidia (CDI): pick
# exactly ONE — both would pass the devices twice.
mybox_dropins := env_var_or_default("MYBOX_DROPINS", "05-user 10-gui 20-gpu 31-nvidia-raw 85-publish-ssh")

quadlet_dir := "/etc/containers/systemd"
unit := mybox_name + ".service"

default:
    @just --list --unsorted

# Build the OCI image into the rootful store.
build:
    @echo ">>> building {{mybox_image}}"
    sudo podman build -t "{{mybox_image}}" "{{mybox_dir}}"
    @echo ">>> done. apply with: just restart"

# Symlink quadlet + network + drop-ins into /etc/containers/systemd.
# Symlinks (not copies) so repo edits apply on the next daemon-reload.
# Name drop-ins to override the default set:
#   just install 05-user 10-gui 31-nvidia-raw
install *dropins:
    #!/usr/bin/env bash
    set -euo pipefail
    SRC="{{mybox_dir}}"; NAME="{{mybox_name}}"; QD="{{quadlet_dir}}"
    LIST="{{dropins}}"; [[ -z "$LIST" ]] && LIST="{{mybox_dropins}}"
    for d in $LIST; do
      [[ -f "$SRC/container/$d.conf" ]] || { echo "ERROR: no drop-in container/$d.conf" >&2; exit 1; }
    done
    sudo mkdir -p "$QD/$NAME.container.d"
    sudo ln -sfn "$SRC/mybox.container" "$QD/$NAME.container"
    sudo ln -sfn "$SRC/container/{{mybox_netfile}}" "$QD/{{mybox_netfile}}"
    # Point the container at the network we just linked. Without this,
    # MYBOX_NETFILE would only change which FILE is installed while
    # mybox.container still named the old one — and the generator drops the
    # container unit entirely when it references a network that is not
    # there. The empty Network= first is quadlet's reset: a bare Network=
    # APPENDS, so without it the container would join both.
    sudo tee "$QD/$NAME.container.d/00-network.conf" >/dev/null <<EOF
    # Generated by just install - do not edit; set MYBOX_NETFILE instead.
    [Container]
    Network=
    Network={{mybox_netfile}}
    EOF
    for d in $LIST; do
      sudo ln -sfn "$SRC/container/$d.conf" "$QD/$NAME.container.d/$d.conf"
    done
    # Declarative: remove previously-linked drop-ins not in LIST (only
    # symlinks into this repo — hand-written local drop-ins are kept).
    for f in "$QD/$NAME.container.d"/*.conf; do
      [[ -L "$f" ]] || continue
      case "$(readlink -f "$f")" in "$SRC/container/"*) ;; *) continue ;; esac
      b=$(basename "$f" .conf)
      grep -qw -- "$b" <<<"$LIST" || { echo "    removing stale drop-in: $b"; sudo rm -f "$f"; }
    done
    # Same for .network files, and this one is not cosmetic: ONE dangling
    # link makes the quadlet generator abort the whole run, so a renamed or
    # deleted .network takes every unit down with it, mybox.service included.
    for f in "$QD"/*.network; do
      [[ -e "$f" || -L "$f" ]] || continue
      [[ "$(basename "$f")" == "{{mybox_netfile}}" ]] && continue
      if [[ -L "$f" ]]; then
        case "$(readlink "$f")" in "$SRC/container/"*) ;; *) continue ;; esac
      else
        continue
      fi
      echo "    removing stale network: $(basename "$f")"
      sudo rm -f "$f"
    done
    sudo systemctl daemon-reload
    echo ">>> installed $NAME.container"
    echo "    drop-ins: $LIST"
    echo "    start:    just start"

# Recreate the podman network from its .network file.
#
# Quadlet creates a network object only when it is MISSING and never
# reconciles an existing one against the file, so editing a .network — or
# switching to a different one that reuses the name — silently keeps the old
# object. Symptom: the container lands on a subnet the file no longer
# mentions. This deletes it so the next start builds it fresh.
net-reset:
    #!/usr/bin/env bash
    set -euo pipefail
    name=$(sed -n 's/^NetworkName=//p' "{{mybox_dir}}/container/{{mybox_netfile}}")
    echo ">>> removing podman network '$name' (it is recreated on next start)"
    sudo systemctl stop {{unit}} || true
    sudo podman network rm -f "$name" 2>/dev/null || true
    sudo systemctl start {{unit}}
    echo ">>> done:"
    sudo podman network inspect "$name" --format '    {{{{.Name}}}} {{{{.Driver}}}} {{{{range .Subnets}}}}{{{{.Subnet}}}}{{{{end}}}}'

# Start the unit — systemd creates the container.
start:
    sudo systemctl start {{unit}}

# Stop the unit — systemd removes the container; /srv state survives.
stop:
    sudo systemctl stop {{unit}}

# Recreate against the current image + drop-ins.
restart:
    sudo systemctl daemon-reload
    sudo systemctl restart {{unit}}

# Unit state, container state, LAN IP.
status:
    -systemctl status {{unit}} --no-pager -n 0
    -sudo podman ps -a --filter "name=^{{mybox_name}}$" --format 'table {{{{.Names}}\t{{{{.Status}}\t{{{{.Networks}}'
    -sudo podman exec {{mybox_name}} ip -o -4 addr show eth0

# Follow the unit journal.
logs:
    journalctl -fu {{unit}}

# Fast shell as USER (podman exec, no PAM session).
# `runuser` inside, not `podman exec -u <name>`: podman resolves a user
# NAME against the image's /etc/passwd as seen from the host, and the image
# bakes no user — the account lives in the /etc overlay, which only exists
# inside the container's mount namespace. `-u 1000` would work; resolving
# the name in there keeps this recipe taking a name.
enter user=mybox_username:
    sudo podman exec -it {{mybox_name}} runuser -u "{{user}}" -- /usr/bin/fish -l

# Full PAM/logind session as USER (login -f, empty-password user).
login user=mybox_username:
    sudo podman exec -it {{mybox_name}} login -f "{{user}}"
