# mybox — build the image and drive the quadlet. Everything about how
# the container is composed lives in mybox.container + container/*.conf;
# this file only builds, installs the unit files and gets you a shell.
# The container is disposable (recreated on every restart/boot); state
# persists under /srv/<name>, which mybox.container binds at /.mybox and
# the pre-init turns into an overlay upper for each image-owned tree.

set shell := ["bash", "-euo", "pipefail", "-c"]

mybox_dir := justfile_directory()

# Must match Image= in mybox.container — the published ghcr reference.
# `just build` tags a LOCAL build over it in the ROOTFUL store (the
# system quadlet reads that store; a rootless build is invisible to it).
# Skipping `just build` makes the quadlet pull the published image.
mybox_image := env_var_or_default("MYBOX_IMAGE", "ghcr.io/aboglioli/mybox:latest")

# Unit name: <name>.container → <name>.service, state at /srv/<name>.
mybox_name := env_var_or_default("MYBOX_CONTAINER", "mybox")

# Default user for `enter` / `login` (created at boot by
# mybox-user-setup.service from MYBOX_* env).
mybox_username := env_var_or_default("MYBOX_USERNAME", "user")

# Network: mybox-nat.network (podman bridge + NAT, works anywhere) or
# mybox-lan.network (macvlan — the container is its own host on the LAN).
mybox_netfile := env_var_or_default("MYBOX_NETFILE", "mybox-nat.network")

# Default drop-in set for `just install`. Persistence is NOT here —
# /srv/<name>/{etc,var,home,srv} is part of mybox.container itself and
# cannot be opted out of. 31-nvidia-raw vs 30-nvidia (CDI): pick
# exactly ONE — both would pass the devices twice.
mybox_dropins := env_var_or_default("MYBOX_DROPINS", "05-user 10-gui 20-gpu 31-nvidia-raw 85-publish-ssh")

# Socket that means the desktop session is ready. Only used with the
# 10-gui drop-in; keep in sync with container/10-gui.conf.
mybox_wayland := env_var_or_default("MYBOX_WAYLAND", "/run/user/1000/wayland-1")

quadlet_dir := "/etc/containers/systemd"
unit := mybox_name + ".service"

default:
    @just --list --unsorted

# Build the OCI image into the rootful store.
build:
    @echo ">>> building {{mybox_image}}"
    sudo podman build -t "{{mybox_image}}" "{{mybox_dir}}"
    @echo ">>> done. apply with: just restart"

# Install quadlet + network + drop-ins into /etc/containers/systemd.
#
# COPIES, not symlinks: generators run before any mount, so a link into
# /home is unreadable at boot and NO unit is generated. Use `just sync`
# to push repo edits afterwards.
#
# Name drop-ins to override the default set:
#   just install 05-user 10-gui 31-nvidia-raw
#
# Copy quadlet + network + drop-ins to /etc, wire the start trigger.
install *dropins:
    #!/usr/bin/env bash
    set -euo pipefail
    SRC="{{mybox_dir}}"; NAME="{{mybox_name}}"; QD="{{quadlet_dir}}"
    LIST="{{dropins}}"; [[ -z "$LIST" ]] && LIST="{{mybox_dropins}}"
    for d in $LIST; do
      [[ -f "$SRC/container/$d.conf" ]] || { echo "ERROR: no drop-in container/$d.conf" >&2; exit 1; }
    done
    sudo mkdir -p "$QD/$NAME.container.d"
    # rm first: install(1) follows an existing symlink and would truncate
    # its target - i.e. clobber this repo on a box installed by the old
    # symlinking version of this recipe.
    sudo rm -f "$QD/$NAME.container" "$QD/{{mybox_netfile}}"
    sudo install -m0644 "$SRC/mybox.container" "$QD/$NAME.container"
    sudo install -m0644 "$SRC/container/{{mybox_netfile}}" "$QD/{{mybox_netfile}}"
    # Point the container at the network we just installed. Without this,
    # MYBOX_NETFILE would only change which FILE is installed while
    # mybox.container still named the old one — and the generator drops the
    # container unit entirely when it references a network that is not
    # there. The empty Network= first is quadlet's reset: a bare Network=
    # APPENDS, so without it the container would join both.
    sudo tee "$QD/$NAME.container.d/00-network.conf" >/dev/null <<EOF
    # Generated by just install - do not edit; set MYBOX_NETFILE instead.
    [Container]
    Network=
    Network={{mybox_netfile}}
    EOF
    for d in $LIST; do
      sudo rm -f "$QD/$NAME.container.d/$d.conf"
      sudo install -m0644 "$SRC/container/$d.conf" "$QD/$NAME.container.d/$d.conf"
    done
    # Declarative: drop what is no longer in LIST. A copy carries no link
    # back to the repo, so "ours" is decided by name — hand-written local
    # drop-ins have no counterpart in container/ and are left alone.
    for f in "$QD/$NAME.container.d"/*.conf; do
      [[ -e "$f" ]] || continue
      b=$(basename "$f" .conf)
      [[ -f "$SRC/container/$b.conf" ]] || continue
      grep -qw -- "$b" <<<"$LIST" || { echo "    removing stale drop-in: $b"; sudo rm -f "$f"; }
    done
    # Same for .network files, and not cosmetic: ONE unreadable entry makes
    # the generator abort the whole run, mybox.service included.
    for f in "$QD"/*.network; do
      [[ -e "$f" ]] || continue
      b=$(basename "$f")
      [[ "$b" == "{{mybox_netfile}}" ]] && continue
      [[ -f "$SRC/container/$b" ]] || continue
      echo "    removing stale network: $b"
      sudo rm -f "$f"
    done
    # GUI hosts can't boot-start (see 10-gui.conf) and get a path trigger;
    # headless hosts keep the boot wiring and need neither.
    PATHUNIT="/etc/systemd/system/$NAME-gui.path"
    if grep -qw -- '10-gui' <<<"$LIST"; then
      # host/mybox-gui.path is valid as-is; only retarget the two
      # host-specific lines.
      sudo rm -f "$PATHUNIT"
      sed -e "s|^PathExists=.*|PathExists={{mybox_wayland}}|" \
          -e "s|^Unit=.*|Unit=$NAME.service|" \
          -e "s|^Description=.*|Description=Start $NAME when the desktop session is ready|" \
          "$SRC/host/mybox-gui.path" | sudo tee "$PATHUNIT" >/dev/null
      sudo chmod 0644 "$PATHUNIT"
      sudo systemctl daemon-reload
      sudo systemctl enable --now "$NAME-gui.path"
      echo "    trigger:  $NAME-gui.path watches {{mybox_wayland}}"
    else
      if [[ -e "$PATHUNIT" ]]; then
        echo "    removing stale trigger: $NAME-gui.path (headless: boot-start)"
        sudo systemctl disable --now "$NAME-gui.path" 2>/dev/null || true
        sudo rm -f "$PATHUNIT"
      fi
      echo "    trigger:  none — starts at boot (multi-user.target)"
    fi
    sudo systemctl daemon-reload
    echo ">>> installed $NAME.container"
    echo "    drop-ins: $LIST"
    echo "    start:    just start"

# Recreate the podman network from its .network file.
#
# Quadlet creates a network object only when it is MISSING and never
# reconciles an existing one against the file, so editing a .network — or
# switching to a different one that reuses the name — silently keeps the old
# object. Symptom: the container lands on a subnet the file no longer
# mentions. This deletes it so the next start builds it fresh.
net-reset:
    #!/usr/bin/env bash
    set -euo pipefail
    name=$(sed -n 's/^NetworkName=//p' "{{mybox_dir}}/container/{{mybox_netfile}}")
    netunit="$(basename "{{mybox_netfile}}" .network)-network.service"
    echo ">>> rebuilding podman network '$name' from {{mybox_netfile}}"
    sudo systemctl stop {{unit}} || true
    # The generated network unit is RemainAfterExit=yes, so it stays active
    # after creating the network and would NOT re-run: deleting the network
    # underneath it just leaves the container starting against nothing.
    sudo systemctl stop "$netunit" || true
    sudo podman network rm -f "$name" 2>/dev/null || true
    # Clear the start-rate limit a failed attempt may have tripped.
    sudo systemctl reset-failed {{unit}} "$netunit" 2>/dev/null || true
    sudo systemctl start {{unit}}
    echo ">>> done:"
    sudo podman network inspect "$name" --format '    {{{{.Name}}  driver={{{{.Driver}}  {{{{range .Subnets}}{{{{.Subnet}} gw {{{{.Gateway}}{{{{end}}'

# Start the unit — systemd creates the container.
start:
    sudo systemctl start {{unit}}

# Stop the unit — systemd removes the container; /srv state survives.
stop:
    sudo systemctl stop {{unit}}

# Refresh what is already installed, without changing which drop-ins are
# selected — safe on a box whose set differs from the default below.
#
# Re-copy installed unit files from this repo (apply repo edits).
sync:
    #!/usr/bin/env bash
    set -euo pipefail
    SRC="{{mybox_dir}}"; NAME="{{mybox_name}}"; QD="{{quadlet_dir}}"
    [[ -e "$QD/$NAME.container" ]] || { echo "ERROR: $NAME.container is not installed — run: just install" >&2; exit 1; }
    refresh() { sudo rm -f "$2"; sudo install -m0644 "$1" "$2"; echo "    refreshed: $(basename "$2")"; }
    refresh "$SRC/mybox.container" "$QD/$NAME.container"
    for f in "$QD/$NAME.container.d"/*.conf; do
      [[ -e "$f" ]] || continue
      b=$(basename "$f" .conf)
      [[ -f "$SRC/container/$b.conf" ]] || continue
      refresh "$SRC/container/$b.conf" "$f"
    done
    for f in "$QD"/*.network; do
      [[ -e "$f" ]] || continue
      b=$(basename "$f")
      [[ -f "$SRC/container/$b" ]] || continue
      refresh "$SRC/container/$b" "$f"
    done
    # ...and the trigger unit, if this box uses one.
    if [[ -e "/etc/systemd/system/$NAME-gui.path" ]]; then
      sed -e "s|^PathExists=.*|PathExists={{mybox_wayland}}|" \
          -e "s|^Unit=.*|Unit=$NAME.service|" \
          -e "s|^Description=.*|Description=Start $NAME when the desktop session is ready|" \
          "$SRC/host/mybox-gui.path" | sudo tee "/etc/systemd/system/$NAME-gui.path" >/dev/null
      echo "    refreshed: $NAME-gui.path"
    fi
    sudo systemctl daemon-reload

# Re-copies first, so edit-then-restart applies the edit.
#
# Recreate against the current image + drop-ins.
restart: sync
    sudo systemctl restart {{unit}}

# Unit state, container state, LAN IP.
status:
    -systemctl status {{unit}} --no-pager -n 0
    -sudo podman ps -a --filter "name=^{{mybox_name}}$" --format 'table {{{{.Names}}\t{{{{.Status}}\t{{{{.Networks}}'
    -sudo podman exec {{mybox_name}} ip -o -4 addr show eth0

# Follow the unit journal.
logs:
    journalctl -fu {{unit}}

# Fast shell as USER (podman exec, no PAM session).
# `runuser` inside, not `podman exec -u <name>`: podman resolves a user
# NAME against the image's /etc/passwd as seen from the host, and the image
# bakes no user — the account lives in the /etc overlay, which only exists
# inside the container's mount namespace. `-u 1000` would work; resolving
# the name in there keeps this recipe taking a name.
enter user=mybox_username:
    sudo podman exec -it {{mybox_name}} runuser -u "{{user}}" -- /usr/bin/fish -l

# Full PAM/logind session as USER (login -f, empty-password user).
login user=mybox_username:
    sudo podman exec -it {{mybox_name}} login -f "{{user}}"
